### ISSUE TITLE
Error on adding package : Could not find package "follow-redirects"

### ISSUE THREAD

**Issue by rhayart** [CMiksche/exchangerates-wrapper#3]
Hi, your library seems really cool, but when trying to install it i got an issue :

```
[1/4] Resolving packages...
error Couldn't find package "follow-redirects@^1.14.4" required by "axios@^0.23.0" on the "npm" registry.
```

After doing : `yarn add exchangerates-wrapper`

Thanks in advance for your answer

**Comment by CMiksche** [comment]
Sounds like a network problem on your side. https://www.npmjs.com/package/follow-redirects/v/1.14.4 Is available on npm...

**Comment by rhayart** [comment]
Oh yeah it seems to be ok now. Sorry for the inconvenience...
